import { Listing, PropertyType, TransactionType, ModerationResult } from '@/types'

const mockModeration: ModerationResult = {
  status: 'auto_approved',
  riskScore: 10,
  flags: [],
  suggestions: [],
  reviewedAt: new Date(),
  reviewedBy: null,
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'listing-001',
    sellerId: 'seller-1',
    sellerName: 'Nguyễn Văn A',
    sellerPhone: '0901234567',
    title: 'Căn hộ 2 phòng ngủ tại Hà Nội',
    type: 'apartment' as PropertyType,
    transaction: 'sell' as TransactionType,
    price: '2.5 tỷ',
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    city: 'Hà Nội',
    district: 'Ba Đình',
    address: '123 Đường Lê Thái Tổ, Ba Đình, Hà Nội',
    description: 'Căn hộ sang trọng, view đẹp, gần công viên Thống Nhất. Nội thất đầy đủ.',
    images: [
      'https://via.placeholder.com/600x400?text=Apartment+1',
      'https://via.placeholder.com/600x400?text=Apartment+2',
    ],
    status: 'active' as const,
    moderation: mockModeration,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'listing-002',
    sellerId: 'seller-2',
    sellerName: 'Trần Thị B',
    sellerPhone: '0912345678',
    title: 'Nhà phố 3 tầng tại TP HCM',
    type: 'house' as PropertyType,
    transaction: 'sell' as TransactionType,
    price: '5.8 tỷ',
    area: 120,
    bedrooms: 3,
    bathrooms: 3,
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 7',
    address: '456 Đường Nguyễn Hữu Cảnh, Quận 7, TP HCM',
    description: 'Nhà phố mới xây, thiết kế hiện đại, an ninh 24/7, gần trường học.',
    images: [
      'https://via.placeholder.com/600x400?text=House+1',
      'https://via.placeholder.com/600x400?text=House+2',
    ],
    status: 'active' as const,
    moderation: mockModeration,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'listing-003',
    sellerId: 'seller-3',
    sellerName: 'Lê Văn C',
    sellerPhone: '0923456789',
    title: 'Dãy phòng trọ cho thuê tại Đà Nẵng',
    type: 'apartment' as PropertyType,
    transaction: 'rent' as TransactionType,
    price: '10 triệu/tháng',
    area: 200,
    bedrooms: 5,
    bathrooms: 5,
    city: 'Đà Nẵng',
    district: 'Hải Châu',
    address: '789 Đường Trần Phú, Hải Châu, Đà Nẵng',
    description: 'Dãy phòng trọ tốt, cho thuê theo phòng hoặc nguyên dãy. Giá cả hợp lý.',
    images: [
      'https://via.placeholder.com/600x400?text=Rental+1',
      'https://via.placeholder.com/600x400?text=Rental+2',
    ],
    status: 'active' as const,
    moderation: mockModeration,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'listing-004',
    sellerId: 'seller-4',
    sellerName: 'Phạm Văn D',
    sellerPhone: '0934567890',
    title: 'Đất nền 500m² tại Biên Hòa',
    type: 'land' as PropertyType,
    transaction: 'sell' as TransactionType,
    price: '1.2 tỷ',
    area: 500,
    city: 'Biên Hòa',
    district: 'Thành phố Biên Hòa',
    address: '321 Đường Võ Nguyên Giáp, Biên Hòa',
    description: 'Đất nền vị trí đẹp, gần chợ, gần trường, hạ tầng hoàn chỉnh.',
    images: [
      'https://via.placeholder.com/600x400?text=Land+1',
      'https://via.placeholder.com/600x400?text=Land+2',
    ],
    status: 'active' as const,
    moderation: mockModeration,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'listing-005',
    sellerId: 'seller-5',
    sellerName: 'Hoàng Thị E',
    sellerPhone: '0945678901',
    title: 'Văn phòng cho thuê tại Hà Nội',
    type: 'office' as PropertyType,
    transaction: 'rent' as TransactionType,
    price: '50 triệu/tháng',
    area: 150,
    city: 'Hà Nội',
    district: 'Hoàn Kiếm',
    address: '654 Đường Hàng Trống, Hoàn Kiếm, Hà Nội',
    description: 'Văn phòng hiện đại, trang thiết bị đầy đủ, vị trí đắc địa.',
    images: [
      'https://via.placeholder.com/600x400?text=Office+1',
      'https://via.placeholder.com/600x400?text=Office+2',
    ],
    status: 'active' as const,
    moderation: mockModeration,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
]
